CREATE TABLE `brand_exposure_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorshipId` int NOT NULL,
	`sponsorId` int NOT NULL,
	`eventId` int NOT NULL,
	`date` timestamp NOT NULL,
	`logoImpressions` bigint DEFAULT 0,
	`digitalImpressions` bigint DEFAULT 0,
	`footTraffic` int DEFAULT 0,
	`socialMentions` int DEFAULT 0,
	`mediaHits` int DEFAULT 0,
	`websiteClicks` int DEFAULT 0,
	`qrScans` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `brand_exposure_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorId` int NOT NULL,
	`sponsorshipId` int,
	`nameAr` varchar(255),
	`nameEn` varchar(255),
	`type` enum('social_media','email','display','video','print','activation') NOT NULL,
	`status` enum('draft','scheduled','active','paused','completed') NOT NULL DEFAULT 'draft',
	`budget` decimal(12,2),
	`spent` decimal(12,2) DEFAULT '0',
	`impressions` bigint DEFAULT 0,
	`clicks` int DEFAULT 0,
	`conversions` int DEFAULT 0,
	`startDate` timestamp,
	`endDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorshipId` int NOT NULL,
	`sponsorId` int NOT NULL,
	`contractNumber` varchar(50) NOT NULL,
	`titleAr` varchar(500),
	`titleEn` varchar(500),
	`totalAmount` decimal(12,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'SAR',
	`terms` json,
	`status` enum('draft','pending_review','sent','signed','active','expired','cancelled') NOT NULL DEFAULT 'draft',
	`signedAt` timestamp,
	`signatureData` text,
	`expiresAt` timestamp,
	`fileUrl` varchar(1000),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contracts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`titleAr` varchar(500) NOT NULL,
	`titleEn` varchar(500) NOT NULL,
	`descriptionAr` text,
	`descriptionEn` text,
	`venue` varchar(255),
	`city` varchar(100),
	`country` varchar(100) DEFAULT 'Saudi Arabia',
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`registrationDeadline` timestamp,
	`expectedVisitors` int,
	`expectedExhibitors` int,
	`sectors` json,
	`imageUrl` varchar(1000),
	`mapUrl` varchar(1000),
	`status` enum('draft','under_review','approved','active','completed','cancelled') NOT NULL DEFAULT 'draft',
	`sponsorshipEnabled` boolean DEFAULT true,
	`totalSponsorSlots` int DEFAULT 20,
	`filledSponsorSlots` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `files` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`filename` varchar(500) NOT NULL,
	`mimeType` varchar(100),
	`sizeBytes` bigint,
	`url` varchar(1000) NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`category` varchar(50),
	`relatedId` int,
	`relatedType` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `files_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorshipId` int NOT NULL,
	`sponsorId` int NOT NULL,
	`contractId` int,
	`invoiceNumber` varchar(50) NOT NULL,
	`description` text,
	`subtotal` decimal(12,2) NOT NULL,
	`vatRate` decimal(5,2) DEFAULT '15.00',
	`vatAmount` decimal(12,2),
	`totalAmount` decimal(12,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'SAR',
	`status` enum('draft','sent','paid','partially_paid','overdue','cancelled') NOT NULL DEFAULT 'draft',
	`dueDate` timestamp,
	`paidAt` timestamp,
	`fileUrl` varchar(1000),
	`zatcaCompliant` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorId` int NOT NULL,
	`eventId` int NOT NULL,
	`sponsorshipId` int,
	`companyName` varchar(255),
	`contactName` varchar(255),
	`email` varchar(320),
	`phone` varchar(32),
	`industry` varchar(100),
	`interestLevel` enum('high','medium','low') NOT NULL DEFAULT 'medium',
	`source` varchar(100),
	`notes` text,
	`status` enum('new','contacted','qualified','converted','lost') NOT NULL DEFAULT 'new',
	`score` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`titleAr` varchar(500),
	`titleEn` varchar(500),
	`messageAr` text,
	`messageEn` text,
	`type` enum('info','success','warning','error','system') NOT NULL DEFAULT 'info',
	`category` varchar(50),
	`relatedId` int,
	`relatedType` varchar(50),
	`isRead` boolean DEFAULT false,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` int NOT NULL,
	`sponsorId` int NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'SAR',
	`method` enum('credit_card','mada','apple_pay','bank_transfer','wire') NOT NULL,
	`status` enum('pending','processing','completed','failed','refunded') NOT NULL DEFAULT 'pending',
	`transactionId` varchar(255),
	`gatewayResponse` json,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sponsor_packages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` int NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255) NOT NULL,
	`tier` enum('platinum','gold','silver','bronze','custom') NOT NULL,
	`descriptionAr` text,
	`descriptionEn` text,
	`price` decimal(12,2) NOT NULL,
	`currency` varchar(10) DEFAULT 'SAR',
	`maxSponsors` int DEFAULT 1,
	`currentSponsors` int DEFAULT 0,
	`benefits` json,
	`assets` json,
	`boothSizeM2` int,
	`vipTickets` int,
	`mediaCovarage` boolean DEFAULT false,
	`openingSpeech` boolean DEFAULT false,
	`categoryExclusivity` boolean DEFAULT false,
	`digitalPromotion` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sponsor_packages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sponsor_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyNameAr` varchar(255),
	`companyNameEn` varchar(255),
	`brandName` varchar(255),
	`contactPerson` varchar(255),
	`phone` varchar(32),
	`country` varchar(100),
	`city` varchar(100),
	`industry` varchar(100),
	`companySize` varchar(50),
	`marketingBudget` varchar(100),
	`targetMarket` varchar(255),
	`website` varchar(500),
	`linkedIn` varchar(500),
	`logoUrl` varchar(1000),
	`description` text,
	`commercialRegNo` varchar(50),
	`vatNumber` varchar(50),
	`verificationStatus` enum('pending','submitted','under_review','verified','rejected') NOT NULL DEFAULT 'pending',
	`kycSubmittedAt` timestamp,
	`kycVerifiedAt` timestamp,
	`kycRejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sponsor_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sponsorships` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorId` int NOT NULL,
	`eventId` int NOT NULL,
	`packageId` int NOT NULL,
	`status` enum('lead','qualified','proposal_sent','negotiation','contract_sent','signed','paid','active','completed','lost') NOT NULL DEFAULT 'lead',
	`totalAmount` decimal(12,2),
	`paidAmount` decimal(12,2) DEFAULT '0',
	`notes` text,
	`lostReason` text,
	`brandImpressions` bigint DEFAULT 0,
	`leadsGenerated` int DEFAULT 0,
	`estimatedRoi` decimal(8,2),
	`logoPlaced` boolean DEFAULT false,
	`boothSetup` boolean DEFAULT false,
	`ticketsDelivered` boolean DEFAULT false,
	`mediaCoverageActive` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sponsorships_id` PRIMARY KEY(`id`)
);
